import type { Metadata } from "next";
import { Prompt } from "next/font/google"; // ใช้ฟอนต์ Prompt
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { ThemeProvider } from "./components/ThemeProvider";
import { CartProvider } from "./components/CartContext"; // ตรวจสอบให้แน่ใจว่า CartProvider ครอบคลุมทั้งหมด

const prompt = Prompt({ subsets: ["latin"], weight: ["400", "500", "600", "700"] }); // กำหนดน้ำหนักฟอนต์ที่ต้องการ

export const metadata: Metadata = {
  title: "Food Restaurant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={prompt.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <CartProvider> {/* ครอบทุกส่วนของแอปพลิเคชันด้วย CartProvider เพื่อให้สามารถใช้ cart ได้ทุกที่ */}
            <div className="flex min-h-screen w-full flex-col">
              <Header /> {/* Header ไม่ควรถูกซ้ำในหน้าลูก */}
              <main className="flex min-h-[calc(100vh_-_theme(spacing.16))] flex-1 flex-col gap-4 bg-muted/40 p-4 md:gap-8 md:p-10 bg-gray-100">
                {children} {/* เนื้อหาจะถูกแสดงที่นี่ */}
              </main>
              <Footer /> {/* Footer อยู่ใน layout ไม่ต้องใส่ในหน้าอื่น */}
            </div>
          </CartProvider> {/* ปิด CartProvider */}
        </ThemeProvider>
      </body>
    </html>
  );
}
